### ISSUE TITLE
GUI loads and cancels audio

### ISSUE THREAD

**Issue by xanbrennan** [kalanda/RPi-MediaLooper#2]
When the Pi boots I get the audio (I have an MP3 playing) starting. Then it stops and the desktop GUI loads. Everything else works flawlessly.

**Comment by kalanda** [comment]
@xanbrennan I guess is because you did set the config (installing Raspbian) to start desktop GUI on boot. Try to disable desktop boot using in terminal `sudo raspi-config`:

https://www.raspberrypi.org/documentation/configuration/raspi-config.md
https://learn.adafruit.com/adafruits-raspberry-pi-lesson-2-first-time-configuration/booting-into-desktop

**Comment by xanbrennan** [comment]
Oh good grief... I knew it was something stupid I missed. Thanks!!!
